// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Participant, ParticipantData } from "./tables/Participant.sol";
import { Depositors } from "./tables/Depositors.sol";
