// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ForceFieldProgram } from "../../ForceFieldProgram.sol";
import { HookContext, IMine, IBuild } from "@dust/world/src/ProgramHooks.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ForceFieldProgramType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "workshop_1", name: "ForceFieldProgra" }))
ForceFieldProgramType constant forceFieldProgram = ForceFieldProgramType.wrap(
  0x7379776f726b73686f705f3100000000466f7263654669656c6450726f677261
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ForceFieldProgramLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ForceFieldProgramLib {
  error ForceFieldProgramLib_CallingFromRootSystem();

  function onAttachProgram(ForceFieldProgramType self, HookContext memory ctx) internal {
    return CallWrapper(self.toResourceId(), address(0)).onAttachProgram(ctx);
  }

  function onDetachProgram(ForceFieldProgramType self, HookContext memory ctx) internal view {
    return CallWrapper(self.toResourceId(), address(0)).onDetachProgram(ctx);
  }

  function onMine(ForceFieldProgramType self, HookContext memory ctx, IMine.MineData memory mine) internal view {
    return CallWrapper(self.toResourceId(), address(0)).onMine(ctx, mine);
  }

  function onBuild(ForceFieldProgramType self, HookContext memory ctx, IBuild.BuildData memory build) internal view {
    return CallWrapper(self.toResourceId(), address(0)).onBuild(ctx, build);
  }

  function _msgSender(ForceFieldProgramType self) internal view returns (address __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0))._msgSender();
  }

  function _msgValue(ForceFieldProgramType self) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0))._msgValue();
  }

  function onAttachProgram(CallWrapper memory self, HookContext memory ctx) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_onAttachProgram_HookContext.onAttachProgram, (ctx));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function onDetachProgram(CallWrapper memory self, HookContext memory ctx) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_onDetachProgram_HookContext.onDetachProgram, (ctx));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function onMine(CallWrapper memory self, HookContext memory ctx, IMine.MineData memory mine) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_onMine_HookContext_IMine_MineData.onMine, (ctx, mine));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function onBuild(CallWrapper memory self, HookContext memory ctx, IBuild.BuildData memory build) internal view {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_onBuild_HookContext_IBuild_BuildData.onBuild, (ctx, build));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);
    abi.decode(returnData, (bytes));
  }

  function _msgSender(CallWrapper memory self) internal view returns (address __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(__msgSender._msgSender, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (address));
    }
  }

  function _msgValue(CallWrapper memory self) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ForceFieldProgramLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(__msgValue._msgValue, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function onAttachProgram(RootCallWrapper memory self, HookContext memory ctx) internal {
    bytes memory systemCall = abi.encodeCall(_onAttachProgram_HookContext.onAttachProgram, (ctx));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function onDetachProgram(RootCallWrapper memory self, HookContext memory ctx) internal view {
    bytes memory systemCall = abi.encodeCall(_onDetachProgram_HookContext.onDetachProgram, (ctx));
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function onMine(RootCallWrapper memory self, HookContext memory ctx, IMine.MineData memory mine) internal view {
    bytes memory systemCall = abi.encodeCall(_onMine_HookContext_IMine_MineData.onMine, (ctx, mine));
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function onBuild(RootCallWrapper memory self, HookContext memory ctx, IBuild.BuildData memory build) internal view {
    bytes memory systemCall = abi.encodeCall(_onBuild_HookContext_IBuild_BuildData.onBuild, (ctx, build));
    SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
  }

  function _msgSender(RootCallWrapper memory self) internal view returns (address __auxRet0) {
    bytes memory systemCall = abi.encodeCall(__msgSender._msgSender, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (address));
    }
  }

  function _msgValue(RootCallWrapper memory self) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(__msgValue._msgValue, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function callFrom(ForceFieldProgramType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ForceFieldProgramType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ForceFieldProgramType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ForceFieldProgramType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ForceFieldProgramType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ForceFieldProgramType) {
    return ForceFieldProgramType.wrap(resourceId.unwrap());
  }

  function getAddress(ForceFieldProgramType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _onAttachProgram_HookContext {
  function onAttachProgram(HookContext memory ctx) external;
}

interface _onDetachProgram_HookContext {
  function onDetachProgram(HookContext memory ctx) external;
}

interface _onMine_HookContext_IMine_MineData {
  function onMine(HookContext memory ctx, IMine.MineData memory mine) external;
}

interface _onBuild_HookContext_IBuild_BuildData {
  function onBuild(HookContext memory ctx, IBuild.BuildData memory build) external;
}

interface __msgSender {
  function _msgSender() external;
}

interface __msgValue {
  function _msgValue() external;
}

using ForceFieldProgramLib for ForceFieldProgramType global;
using ForceFieldProgramLib for CallWrapper global;
using ForceFieldProgramLib for RootCallWrapper global;
